version: '3.7'

services:
  api:
    build:
      context: ./vue_backend
      dockerfile: Dockerfile.prod
    command: gunicorn -c gunicorn_config.py vuebackend.wsgi:application
    container_name: vue_api
    volumes:
      - static_volume:/usr/src/api/image
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - django-nginx
  redis:
    container_name: vue_redis
    restart: always
    volumes:
      - ./redis.cof:/etc/redis/redis.conf
    ports:
      - 6379:6379
    image: redis
    networks:
      - django-nginx
    command: redis-server /etc/redis/redis.conf
  db:
    container_name: vue_db
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
    networks:
      - django-nginx
  nginx:
    container_name: vue_nginx
    build: ./fontend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    volumes:
      - ./certbot/etc/letsencrypt/live:/letsencrypt/live        # 当前证书目录
      - ./certbot/etc/letsencrypt/archive:/letsencrypt/archive  # 历史证书目录
      - ./dhparam-2048.pem:/letsencrypt/dhparam-2048.pem
      - static_volume:/home/image
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    networks:
      - django-nginx

networks:
  django-nginx:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
